name = "Codemonkey"
license = "MIT"
licenselink = "https://github.com/jdollar/codemonkey/blob/master/LICENSE.md"
description = "Theme style generated for jdollar.github.io"
homepage = "https://jdollar.github.io"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "Joel Dollarhide"
  homepage = "https://jdollar.github.io"

# If porting an existing theme
[original]
  name = "Joel Dollarhide"
  homepage = "https://jdollar.github.io"
  repo = ""
